# Site settings
title: MongoDB Design
email: design@mongodb.com
description: > # this means to ignore newlines until "baseurl:"
  Repository for MongoDB Design thinking, projects, and resources.
baseurl: "/design" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
dribbble_username: mongodb

# Build settings
markdown: kramdown
